web:
    image: nginx:latest
    ports:
        - "81:81"
    volumes:
        - ./backend_1:/backend_1
        - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    ports:
        - "9000:9000"
    volumes:
        - ./backend_1:/backend_1      
